build:
  image: library/node
  commands:
    - npm install
    - npm install mocha -g
    - mocha spec/behavior
    - mocha spec/integration

services:
  rabbit:
      image: arobson/docker-rabbitmq

